export const SLOT_SHOW_RESET = 'SLOT_SHOW_RESET'
export const SLOT_SHOW_SET_ERROR = 'SLOT_SHOW_SET_ERROR'
export const SLOT_SHOW_SET_RETRIEVED = 'SLOT_SHOW_SET_RETRIEVED'
export const SLOT_SHOW_TOGGLE_LOADING = 'SLOT_SHOW_TOGGLE_LOADING'
