export const LOCATION_SHOW_RESET = 'LOCATION_SHOW_RESET'
export const LOCATION_SHOW_SET_ERROR = 'LOCATION_SHOW_SET_ERROR'
export const LOCATION_SHOW_SET_RETRIEVED = 'LOCATION_SHOW_SET_RETRIEVED'
export const LOCATION_SHOW_TOGGLE_LOADING = 'LOCATION_SHOW_TOGGLE_LOADING'
