dist: trusty
branches:
  only: app
env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - TERM=dumb
  # gitusername
  - secure: tAFeuO4fqT+S+Vv+TcdXk4LRlcbsDEZbkShzxnzw3b0QFgQyaotzzQrDaW9S6KPO8knGy7RQoHEavS7wXSgis5h/fRnNiLWo3MoykdKvjx0TwTt7yTaDbgvI2H/xo8zE6DFU8jqH4KVwBq5LFikUJd0hx7uqw86IrR9kYj5R563UZqEacfsR5BWrYWqX5WwZInMnCY6SesKyL3q6F60D6z6Blwdq0evsj05oHWfxmZeSbzboOUg/Is6IBtUGMQRrWGsAdR4x73SiZ9APDfIB4C7oeput+GfOZPjTDoDt8defL6+IyLhw7kqcgQUhA9Lu+Ke2H/0KgHqBk7W1WDeh36s3DIv7MwkhQU+3ks1jdbs0dFWVmdm/yF+GCWy/sEdtFEzCfBh0o0kKfujauJx+T0A/GugaHlTN2fhFXvJ0XHrkoNjsQnNlzWyz/2gmiHLpK9ASFovrrNioq2achgisOlym3Kq10CdaGkfYNN8jHzzXaWVaS00ugMPIcAE4KbQmwav0AN+C9DwplO/yan4bai7/y5roYGRsR8z/MiZJAXH40bFGl8oI0Xl+1zTURR1J0/qKp8DJgZG8XLFWAWfoZOWouvZDNQqHWQU6JLWQgL5GFdhI0PcYZD7OSUEwAzbg19Ko4Lj+S3DhoJCpqP4/7tAmkd8FofCAmdAKXyToa7c=
  # gitemail
  - secure: rayt52s00RAeAtR0THQs2tAmbb5d0UgJscOodMSNOoNbo7Mdn81TMZJBaOr0hRkv2hS/Eq36IliYHduKL79/mlJqIkpWPLXLI+GXn3zMTfanoq7oRyVYS0ToQk8AZ1Uva6G314TscaP/8QYWaRw4R5rj0SPTBlEp7uCg/uQfQltZeyglRX+CbUh7VgNWmM3zDRpO2Pr3kEOd6rRNgtAigUNYYq6C1hWJD4NQMdi65vPFAXMV5cQhAh7w/IvYeRSneFcxlFo7InxEx2Rm/rn/Wh0aDggljyaQSbYW1WpwUNssrNhmLNdJCd/KNMQoW0MHU0uZcawvvc8m0vDmyuArMSMTGBV4ujISZJjIOO6Jy6LEESALMDoHccsrljs7DmLTfQOF5ITEpzVm87xss7+2/oz9rewFyd2PTjBRCVcT5M3xhDThS0xFXBsM2/uExL0IZY1otwfBPVj2nmSQkBRvXHEQj6qgALwG0mp1WueE5OKZZLHoCrb3wyvk76jwovAvOolizhFWKnQ1Iz3Nv1AjRS5TjuVI3Z98TMCxNcQC9nwdzopjCQH4DHzvnyvYI6arcyEt+2z3fUKP2Qo9oKK2+l3U4AUUy+sWuk6xYYqnS+2wgg9VQ1hsOBkaafrN3EFnDXQEx3NfIk4zAA2GngKOMNqC7C9XuggxXE7dL9vCIyU=
  # storepass
  - secure: QPcVS/eMqGLfQbaWLJvCQH+KzVweAKz/lZ5G/Z8pl5tH1+ReqeysvXp1Nt+9k/HGRMLxrFCnkzamNUuf7OyO1o+itdNAeH+nxseKdp2sR7Q60SOzPkkfFdHX58tliaRaqkLybgZhd+tDJw4qoP+nApWwrKmIWem+OfTO0WTGky+ewrjur4um6ocyKetXVCC4syzxNQTZyGay8yrKXcYCYywkyvtsq5kFRdldsY7qS7XzDDVsULgCtlp+T08MaCloUU6j9qDvoCnwW9csNeDNd3f79rt1/HPiOdjVzTNZ6GeeDkIpqApRNv+lZRKNjVyG+XDvvE7VEJYJZHh7Vy6Pj3meSaLh+P7jdWc6BPZ8IMnNJyWuTuoPJo/AeFjNyX6M92mKYr1U6CgGS2KIPMdr3cUzFMPAe7JCyVlHhfZl7iObvEOELrggpdxYXj74YQG7outeRFMcpOJZs997CaT2rEi57aut8lJlSxhUbdmC2Fxf0QvR2XQA6bG/x115VGwr0wAmuVmlmEfkWCElSgpHQB6ZfXSyQoupj+po//eZb6Ei323pW1vXmKCrbmy/nrWlDvidjjFhTWJ8d+DnHVgSVguXt031luAfAFe4L7qX23hlWFOPYKHlnmoovyd9UEH1f5jF/9MlXqpTmGkH/YLxFGE4mLzQd115W1lNEDX3UEc=
  # keypass
  - secure: yZ3yFpDqo1baosTwhttl9Vlx2pbPXa9uAI9OGEZDD/KHqavdnoFq1ItOheZdYXz6yuNkyOsMKEPDgbURgPQLjUsG5JUSxDjBt2XbJhLiVmpy4Ur4wX9x11MmAMuoEjDj4yFO1POpg+NszFpP4OW4+BryIuyOOWdyFEIRRE9keDzelcLTedltQT+AeV8bdJeb2CMoBiHd6VOltceUEBaiXiK9BUJUhg7c+c+0wpGU5Vh3FnhLc5zmMWMe5PVVxn9hI4g0sB7vUmg1johEMCkcH31IebhdUX7hxH9b9gj4BeZjJ63SoRljZCJE10cKd1T8+3RhZXtP1nU+c3RgwinAFbbod1RF2FU5MNNEZfJVGQ4SYM3RtmWRfuidjRxTmgEf9222XkRPzJbNiK/CqXbxWDWifyX/eHHoOBBkIFu0f9Q2OweCiX1LeHe9by8Ng/bGgpJw8NhL70fMzrTdoQlRBn0/2rY9F8+tkbkekp9RxugATh/g3WnBsxp+D8RgM+PXdZ5o4QqRCzblrvyOFfxyqHTDmWkA77c1UC8Jnc6Oac/tyh9+ZDDF36Tj+0J3hsXdnO2wTAxKMkTnIBpuyzLMLEiJbO2McIldGbOteK4mOQRt7ttfNV4vsysuLNDdkOOKVjZzvBdjuQhOTWKoTdkBwOSdcaTXksZuoTu2sWQIOmA=
  # iosDeveloper
  - secure: hmlHnPPjAI+U0/PYhJwk9vlZBFToUrtRF6WbJ4SC7Elc01S5/8C/AGERo3aIRF8S1mtKVPzHNg3VcYRGeG2l3CuBJbnhnb0O6wcjtv+7WJwaAOFBtNv8Y4qD9e0lpAASeiwqwQYVZovj87tfQVyDvqLRiFvdDll8XjidrSWrnbOeEKXD3RLqPLowbdmVN2VQk+SzqO8VXMw0ZJywV7HrvreFCH9ddI3atlh+HXX8q8aAhGeyddJohgug3C7dWF/cbeXD2OQJAsQ9fjkW2ON2BVfbhSM1ZJG9aSaN238yBIjvCHGtgAaJA2LvABnOq8piOJ4LfwKr46NBoK3fcrL2L8nNEHbhces77VjQuHE0A8mmmvBEo2n3/cKiq3WH6W5uKG5BQZIZs8PcBYdzk65ueAabRxIG42XlREDfwFgFfuu3PaKnfWQ3raBzqOUDJBQ+Zz2H52oakC/kvgKcxMpEuO4Mjwck404Dx7xUvg+sUKlU3pLapc9yrH5e32gnMabuMbYQjW+Oq3DCqzr69qn3bW2QPoR+RjQ/dNdsUpwRulAYi1OMQ09CHHOwk57ZRq0VZIxVndQ5kEvavASzbcD3MMuIM6b51zTu3ZO5teiUASkNVQKAMdEMUaLiaZHfyehvkHchDzrP2EeQdAme2x4OZQltNd8rrw8B0yNEE5xnAbs=
  # iossignkey
  - secure: 15jfRUxEczZHSeN8ArUbwHRW9/29tONqURf9H91UA+BkcrbONL1YRpqEbuArTx91ruoSC8tD7CmXch3XCww3BzJ3CepIDQLRlYoxGvAAKsqCGMoifki0nlsL8SvNTHRLBFfmiGDPL9LqYm/mG5JIXTsdXfiObynBoyod/kj8JuyiV3Gt/+I9mkiC/pKLkf2gVbsb6KEOWZmgcZOv1yZREybsjAzyvP3SfFKZKtXaAH3AFNFmpc0QyqOItCEMNrJbnA+/Gj7mZ2Ly2K8U2zg4dYPVN1LQzTweZcJsp5wfF+cprxnC5IOFCPFMnVoinNtJ1YrOL4C5DIcXAqWiMg+LuScedZfTrPiMWAH3gc7NO2ojGJqnzUw/5zxVbjzFk+PijiTSbWjolF8FxO0xpapVWrZdMOdx/OSLj2Kqse1EBr+mx2LB+c5ugqtAOb5xzw8tMqj5Og67XSN+0w+l6wTwXtPyQYakf5EcnCwkPdkuQ4FyQixOz3ATNoN9tv0/gqNbEyl+PZw+SrhBNVaQDQGbXsDJFeaI8EoB33li9VjKreFgITtZzx5B/F9VzUgjUspfe1l+kGTb9Go3um8Eqn885kuZjR0QwL2eZ/IlSr+jY7BoJ+KabaSyx6ia0iZdfr38ZkJ47BBHY/Mankf3v0pyZ/G+76rE0auGzJHi/9SnMGg=
  matrix:
  - nodejs_version=12
language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - extra
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- openssl aes-256-cbc -K $encrypted_a57fb8741d35_key -iv $encrypted_a57fb8741d35_iv
  -in mobile/app-secrets.tar.enc -out mobile/app-secrets.tar -d
- tar xvf mobile/app-secrets.tar
#- keytool -exportcert -list -v -keystore android-chrisphdcccom.new.keystore -storepass "$storepass"
- nvm install $nodejs_version
- npm install -g cordova
- node --version
- npm --version
- gradle --version
- npm install
script:
- export MOBILE_VERSION=$(grep -Po "MOBILE_VERSION = '\K.*?(?=')" nuxt.config.js)
- export MODTOOLS_VERSION=$(grep -Po "MODTOOLS_VERSION = '\K.*?(?=')" nuxt.config.js)

- mkdir releases

- npm run fdapp
- mkdir ../iznik-nuxt-app
- cd ../iznik-nuxt-app
- ln -s ../iznik-nuxt/mobile/freegle/android/config.xml config.xml
- ln -s ../iznik-nuxt/mobile/freegle/android/package.json package.json
- ln -s ../iznik-nuxt/mobile/freegle/icons icons
- ln -s ../iznik-nuxt/mobile/freegle/package-assets package-assets
- ln -s ../iznik-nuxt/mobile/freegle/scripts scripts
- chmod +x scripts/before_build.sh
- cp ../iznik-nuxt/google-services.json google-services.json
- ln -s ../iznik-nuxt/dist www
- cordova platform rm android
- cordova platform add android
# Build debug build
- cordova build --debug -- --keystore="../iznik-nuxt/android-chrisphdcccom.new.keystore" --storePassword="$storepass" --password="$keypass" --alias="Freegle Ltd Chris"
- cp platforms/android/app/build/outputs/apk/debug/app-debug.apk ../iznik-nuxt/releases/Freegle-app-$MOBILE_VERSION-debug-$(date +'%Y%m%d%H%M%S').apk
# Build release build
- ls -l platforms/android/app/src/main/res/drawable-hdpi/
- cordova build --release -- --keystore="../iznik-nuxt/android-chrisphdcccom.new.keystore" --storePassword="$storepass" --password="$keypass" --alias="Freegle Ltd Chris"
- cp platforms/android/app/build/outputs/apk/release/app-release.apk ../iznik-nuxt/releases/Freegle-app-$MOBILE_VERSION-release-$(date +'%Y%m%d%H%M%S').apk
# Publish to Google Play beta track
- sed -i "/3.3.0'/aclasspath 'com.github.triplet.gradle:play-publisher:2.0.0-rc1'" platforms/android/build.gradle
- cp ../iznik-nuxt/mobile/build-extras.gradle platforms/android/app
- cp ../iznik-nuxt/api-freegle-google-play-deployment.json platforms/android/app
- cd platforms/android
- ./gradlew app:publishReleaseApk || true # Ignore errors
- cd ../..

- cd ../iznik-nuxt

- npm run mtapp
- mkdir ../iznik-nuxt-mt
- cd ../iznik-nuxt-mt
- ln -s ../iznik-nuxt/mobile/modtools/android/config.xml config.xml
- ln -s ../iznik-nuxt/mobile/modtools/android/package.json package.json
- ln -s ../iznik-nuxt/mobile/modtools/icons icons
- ln -s ../iznik-nuxt/mobile/modtools/package-assets package-assets
- ln -s ../iznik-nuxt/mobile/modtools/scripts scripts
- chmod +x scripts/before_build.sh
- cp ../iznik-nuxt/google-services.json google-services.json
- ln -s ../iznik-nuxt/dist www
- cordova platform rm android
- cordova platform add android
- cordova build --debug -- --keystore="../iznik-nuxt/android-chrisphdcccom.new.keystore" --storePassword="$storepass" --password="$keypass" --alias="Freegle Ltd Chris"
- cp platforms/android/app/build/outputs/apk/debug/app-debug.apk ../iznik-nuxt/releases/ModTools-app-$MODTOOLS_VERSION-debug-$(date +'%Y%m%d%H%M%S').apk
- cordova build --release -- --keystore="../iznik-nuxt/android-chrisphdcccom.new.keystore" --storePassword="$storepass" --password="$keypass" --alias="Freegle Ltd Chris"
- cp platforms/android/app/build/outputs/apk/release/app-release.apk ../iznik-nuxt/releases/ModTools-app-$MODTOOLS_VERSION-release-$(date +'%Y%m%d%H%M%S').apk
- cd ../iznik-nuxt
- rm mobile/app-secrets.tar android-chrisphdcccom.new.keystore google-services.json GoogleService-Info.plist

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_deploy:
- git config --local user.name "$gitusername"
- git config --local user.email "$gitemail"
- export TRAVIS_TAG=Travis-builds-$MOBILE_VERSION-$MODTOOLS_VERSION-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)
- env | grep '^TRAVIS_TAG='
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: S+1f7ZdQf6C/dH8Cx0i/gtX1hko6xRE9my5j4Kvp9vc5K/frbQGWEM8eqKOmVAvVs+eoN6sFO+tv6mUyRZ4pFzOxxLlVSd0taEgf9NuIxrmclMbAa9f6TpA0g5QTZH0ARYZg5pr9gX4HpKlYlkoO0Roac8VK6d1yO2FFK5eN+KO3+NPCvSA0vIJip4BYTBKCzmDC/AmZWhlBaQSZUVpv5kiItiPO8jM5a5FE+KmDZ0bPBr6t41CFHTivJ5iKt+AfIkALa8er4WMteXCLI8yRt6T7jut8oIDGx5awCtve4v5LL+gTh39XSTdSsEyUCmP395W1CxXT6HjvIIVc4yvqmZ+3KEdM6MuayZZsHbcooqtEC5hht/OQ147eEpV0MZ+Ebn2as0wFcy4783KF9HxX3RppyA4ptVj91baBl99s1c8i11pti7i45dT82l5D71CDhwAfhtMG9CDfPvkHcb9q9J1jN8pYmi39h9iDJS7O7a1XbePJIM33yUrO9uq2w5Id9aIWBlyECMiPNZe1PqTlJlUzGbeSkvoKvj1TzUyiBCYMrJMQoRwAaaeZbR2NkeXGgKwCmMAAsQGHs0hbEDnIrRyp/0L+jyvkiZEiC0ffKYRdu5P2VOGi7DkDu0SCeChUW7dndzXLckMpPE7o92EWXkzXJmzqIt7JuTq08+ngyJU=
  skip_cleanup: true
  file_glob: true
  file: ./releases/*.apk
  on:
    repo: Freegle/iznik-nuxt
    branch: app

