dist: trusty

env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.2
    - TERM=dumb # Keep gradle from crapping all over the log
  matrix:
    - nodejs_version=12

language: android
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

node_js:
- 12
branches:
  only: app
before_install:
- openssl aes-256-cbc -K $encrypted_a57fb8741d35_key -iv $encrypted_a57fb8741d35_iv
  -in mobile/app-secrets.tar.enc -out mobile/app-secrets.tar -d
- tar xvf mobile/app-secrets.tar
- nvm install $nodejs_version
- npm install
- npm install -g cordova
- node --version
- npm --version
- gradle --version

script:
- npm run fdapp
- mkdir ../iznik-nuxt-app
- cd ../iznik-nuxt-app
- ln -s ../iznik-nuxt/mobile/freegle/android/config.xml config.xml
- ln -s ../iznik-nuxt/mobile/freegle/android/package-json package-json
- ln -s ../iznik-nuxt/mobile/freegle/icons icons
- ln -s ../iznik-nuxt/mobile/freegle/package-assets package-assets
- ln -s ../iznik-nuxt/mobile/freegle/scripts scripts
- cp ../iznik-nuxt/google-services.json google-services.json
- ln -s ../iznik-nuxt/dist www
- ls -l
- cordova platform add android
- ls -l platform
- ls -l platform/android
- cordova build
