language: objective-c
osx_image: xcode11
env: nodejs_version=12
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_a57fb8741d35_key -iv $encrypted_a57fb8741d35_iv
  -in mobile/app-secrets.tar.enc -out mobile/app-secrets.tar -d
- tar xvf mobile/app-secrets.tar
- nvm install $nodejs_version
- npm install -g cordova
- node --version
- npm --version
- npm install
script:
- export MOBILE_VERSION=$(grep -Po "MOBILE_VERSION = '\K.*?(?=')" nuxt.config.js)
- export MODTOOLS_VERSION=$(grep -Po "MODTOOLS_VERSION = '\K.*?(?=')" nuxt.config.js)

- mkdir releases

- npm run fdapp
- mkdir ../iznik-nuxt-app
- cd ../iznik-nuxt-app
- ln -s ../iznik-nuxt/mobile/freegle/ios/config.xml config.xml
- ln -s ../iznik-nuxt/mobile/freegle/ios/package.json package.json
- ln -s ../iznik-nuxt/mobile/freegle/icons icons
- ln -s ../iznik-nuxt/mobile/freegle/package-assets package-assets
- ln -s ../iznik-nuxt/mobile/freegle/scripts scripts
- cp ../iznik-nuxt/GoogleService-Info.plist GoogleService-Info.plist
- ln -s ../iznik-nuxt/dist www
- cordova platform rm ios
- cordova platform add ios
