dist: trusty

branches:
  only: app

env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.2
    - TERM=dumb # Keep gradle from crapping all over the log
  matrix:
    - nodejs_version=12

language: android
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
- openssl aes-256-cbc -K $encrypted_a57fb8741d35_key -iv $encrypted_a57fb8741d35_iv
  -in mobile/app-secrets.tar.enc -out mobile/app-secrets.tar -d
- tar xvf mobile/app-secrets.tar
- nvm install $nodejs_version
- npm install
- npm install -g cordova
- npm install -g q
- node --version
- npm --version
- gradle --version

script:
- npm run fdapp
- mkdir ../iznik-nuxt-app
- cd ../iznik-nuxt-app
- ln -s ../iznik-nuxt/mobile/freegle/android/config.xml config.xml
- ln -s ../iznik-nuxt/mobile/freegle/android/package-json package-json
- ln -s ../iznik-nuxt/mobile/freegle/icons icons
- ln -s ../iznik-nuxt/mobile/freegle/package-assets package-assets
- ln -s ../iznik-nuxt/mobile/freegle/scripts scripts
- cp ../iznik-nuxt/google-services.json google-services.json
- ln -s ../iznik-nuxt/dist www
- ls -l
- cordova platform rm android
- cordova platform add android
- ls -l platforms
- ls -l platforms/android
- sh ./scripts/before_build.sh
- cordova build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
