dist: trusty
branches:
  only: app
env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - TERM=dumb
  - secure: k757wZO6GgzqINhfjN7DHx8Y48RC2cb2XLSkRahTIxNUwfUnIOIR5liAztLYPzq7IZJkvQe1o2DMSMlEc3U26qvtMyV3M+3FzBRXHzlwYMAW1S5JX90cHQXVI1n77TfqV5Qjt4x0lczia4+hj9u7pLg4wbOtZ4MC8B8S4FKXJdVnBwRW80x6f21HUCfUMNlXFqbihf3NTevv2zzEaytFcjx3IT06CzkKSpIiQ/zyi8iGlqU+k3Bx3brhGmXmAvVK1FG3H8WRHPTi87SDiqLitQQv/RmwHyRwne4Ok8FnMmCynFjFugdn1uyVRPtV16R3hMsPAFacc6RRzcyujLu+JIVdxs0tDiCAO7VnDPlDIy/M5sxnrRll+qMz9d/C9aFrd83OYKQ3Uts9rlJw5BoUPIH7oez3rky1rzRc9YxgQPoFDGxyRgtyLda1eugxzDBiCGzOv2O6//szGJAbiQwkd0D4+T3+JKiXZ3E/PjKJ0sBg+q8k2zJCi+SbsD/Z5bOJ/uVBRvSFEDSCF41zKRiMioj06/GzNN2gmtM/PilblQfgXaWa7GxzHBkT+JWUXmI5jmuovz2qAu5T7apPXka/UDw4JJkBQtktdecVUnD1ruIu7tAhjJZEU5GOTJwXXGohtJquZ9qRPnnAfEpI//vqre7X+4hgx4d/zgmm/JAWJXs=
  - secure: oTRLRVoflU7QY2qJXFhGZrhJDzVMJBqtiffUPOiQvADWr6M3OwbsbyAQLbinRww4fz6m2OX6HXZJ7xOQ5w1xlPJBVt8qSwwefIgS6Iw0ZS6Pk1upqUIygzTaZDQROz/8PpZfmD/GDa+9trm376iCr8u709aWopTW2GE5dpZ8t0dQReIkfV5pF9O1CUMUiTlfHN9Sz0ljMnxTshpxo4LdfgsJTUqMYgH6fZN5fOxSH5VAoZ744+GDHDnOGF3ncw9lp6q0bw2fxl96jneYOZaloCADlxmvKfzFYCEkm/ECoJOqvqjN6ClB41jm8IlDC12r91Lz7TuQxAs/CPqmSjc6Ayreo2NvdggwF2x870jwghwc1H8aupPaWvv1nenZbHXsDZGMxXtlvLODbPPVHpBorQ4OvXoidIZnkgvLOuq8YIlnTwmFdxYhjaE7iV3XdWDE2GbvJrlt6m45k5OXqqz4lqsP08rdGI2aYMZsLjGMbEf5X4eTS6jeISiApWiDie1DCvf6GEOA1D146r6nFrvloEwpl6NAlsgsMoGxdJXdAQNSfqjzq9ZZI63TKfgOmQDYvVFr0GjTdKh1nKVtgUJ12w0mhSVjNRPqf267mwQkMpJl7ANzFrZecuVMkawDggXeTGqRVcCXCvso0atiQv7mN1iMIXD71LhLezT7S2milOI=
  - secure: yoKdyQEyxO5YJqyOB838uxqzykT9A3jWTdwKvcHiuQuJR7301fYtJ5KgNIsLVZ4ZZph78Ap/sAt9sKDXF7J3lZpx8JIRZ7Vf0u5A80Xr/zpmX5alVveY9EYzUlIp/O7tCY500t/w64izS44Xpf3jatuGMI9cdxGV5e8mbTkOc5HOi47ZhUUiPChwIhzJEneEKceNV7rKYBi4Jv2I6mANs3ltWeON/Yh777LNNyw8pqrAbo2mv6oae5O/GWrtGwOVscKv+0MteOMHBpnIkkqDUfIIocTbWOs+ZZAdaDulzEj2ZkObk1sKO22KcUa3Nd+FJ/0kyILLbwJ5JyIuXc9ubLjrbKMEd3YT7vhmIbhFa5KIQ7PPCyOYbXjtmozZOhvRsSSHA1+CYKykY5mMt9wWyQyVkZ0QNGki4KkDmRbOc6Gu+DnPKL5Jtlmf7X99w5J55BnA8nZR7ulV0cpyS2skxFWjJ3j9H2H/1MuDqdW7D4dD+jmdIIN2WnvP3WHOjQiSZeb36949AZF2wDvO5XP7ihaDH7KFUBPpVNcJnGBsVEAU5ZWSTlipAYOCHkVyPXQIaMpphS8/b61gJB2qnQ2H4/gIkvKEGqmCjM3OopoKhbXyCeLwUF//uKCu+ImeLMJFFipOTb7EWJ58FBJm98JRC1O0E+jEx73JFi4gUmp3hK0=
  - secure: tAFeuO4fqT+S+Vv+TcdXk4LRlcbsDEZbkShzxnzw3b0QFgQyaotzzQrDaW9S6KPO8knGy7RQoHEavS7wXSgis5h/fRnNiLWo3MoykdKvjx0TwTt7yTaDbgvI2H/xo8zE6DFU8jqH4KVwBq5LFikUJd0hx7uqw86IrR9kYj5R563UZqEacfsR5BWrYWqX5WwZInMnCY6SesKyL3q6F60D6z6Blwdq0evsj05oHWfxmZeSbzboOUg/Is6IBtUGMQRrWGsAdR4x73SiZ9APDfIB4C7oeput+GfOZPjTDoDt8defL6+IyLhw7kqcgQUhA9Lu+Ke2H/0KgHqBk7W1WDeh36s3DIv7MwkhQU+3ks1jdbs0dFWVmdm/yF+GCWy/sEdtFEzCfBh0o0kKfujauJx+T0A/GugaHlTN2fhFXvJ0XHrkoNjsQnNlzWyz/2gmiHLpK9ASFovrrNioq2achgisOlym3Kq10CdaGkfYNN8jHzzXaWVaS00ugMPIcAE4KbQmwav0AN+C9DwplO/yan4bai7/y5roYGRsR8z/MiZJAXH40bFGl8oI0Xl+1zTURR1J0/qKp8DJgZG8XLFWAWfoZOWouvZDNQqHWQU6JLWQgL5GFdhI0PcYZD7OSUEwAzbg19Ko4Lj+S3DhoJCpqP4/7tAmkd8FofCAmdAKXyToa7c=
  - secure: rayt52s00RAeAtR0THQs2tAmbb5d0UgJscOodMSNOoNbo7Mdn81TMZJBaOr0hRkv2hS/Eq36IliYHduKL79/mlJqIkpWPLXLI+GXn3zMTfanoq7oRyVYS0ToQk8AZ1Uva6G314TscaP/8QYWaRw4R5rj0SPTBlEp7uCg/uQfQltZeyglRX+CbUh7VgNWmM3zDRpO2Pr3kEOd6rRNgtAigUNYYq6C1hWJD4NQMdi65vPFAXMV5cQhAh7w/IvYeRSneFcxlFo7InxEx2Rm/rn/Wh0aDggljyaQSbYW1WpwUNssrNhmLNdJCd/KNMQoW0MHU0uZcawvvc8m0vDmyuArMSMTGBV4ujISZJjIOO6Jy6LEESALMDoHccsrljs7DmLTfQOF5ITEpzVm87xss7+2/oz9rewFyd2PTjBRCVcT5M3xhDThS0xFXBsM2/uExL0IZY1otwfBPVj2nmSQkBRvXHEQj6qgALwG0mp1WueE5OKZZLHoCrb3wyvk76jwovAvOolizhFWKnQ1Iz3Nv1AjRS5TjuVI3Z98TMCxNcQC9nwdzopjCQH4DHzvnyvYI6arcyEt+2z3fUKP2Qo9oKK2+l3U4AUUy+sWuk6xYYqnS+2wgg9VQ1hsOBkaafrN3EFnDXQEx3NfIk4zAA2GngKOMNqC7C9XuggxXE7dL9vCIyU=
  - secure: aogwkBJ4qxokaLKsnI1+AHeCcmxtA/7jUVv3D6jWFVhh14qLWY9wAuyeI3JS/uK3QkHmjO3HIrt8DYPIhTjy8gwqHtb3P359fIh+mNnpbKNKeXbjkdHveOgChJG9y+e/Rs8dS7p+yuuietf+nVxauzb/Odx20hcqn8YOGUErnbLeKWJgru/XldZi2yrk/hqkG15tdjs+b+18MDN+7oQleZ7wSlITPev3B/DHBPWB00Ez2cIZ7PjPH8s57kMAk7/w5J+LMYdhs7IsXc20qRjq8GjJunhcsUdxjUvqvrPTKcbpV+cuu8mpJmikCitgwDXIee7meLl+h9qZd6pUawL3elt87fKoML4PAaJlqfYTqjsVhK03bVTBWPz8dbjYqVwqUy81wFzCmRcIr5VXw9YflgxYLjP8bLFSKnU8AW6kvkqXnWc/+8gyz1DSxJ4FT3YsfdaYC6pjB19k3s94JNi5x85Hd45U9TyYH3Lq6LW1V9gnkp7TfDniAfXKFU8iSgag0tGdas7qMGXXaDSxS6c7C2Z9HlhWCQZHmwYr9qneTdUg3LAoOVjRVD9e/6salt1uclD0mHhEsQcFtO2qYLmOLqQ++EMbncUdVhGfKFr4ycKGvbc7k65xDIX2s6VMMnjrwgq6fS05t6SGd8lDRI6Y5Rvpl5sNY7TQ8pgTMLQcbyY=
  matrix:
  - nodejs_version=12
language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - extra
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- openssl aes-256-cbc -K $encrypted_a57fb8741d35_key -iv $encrypted_a57fb8741d35_iv
  -in app-secrets.tar.enc -out app-secrets.tar -d
- openssl aes-256-cbc -K $encrypted_a57fb8741d35_key -iv $encrypted_a57fb8741d35_iv
  -in mobile/app-secrets.tar.enc -out mobile/app-secrets.tar -d
- tar xvf mobile/app-secrets.tar
- nvm install $nodejs_version
- npm install -g cordova
- npm install -g q
- npm install
- node --version
- npm --version
- gradle --version
script:
- npm run fdapp
- mkdir ../iznik-nuxt-app
- cd ../iznik-nuxt-app
- ln -s ../iznik-nuxt/mobile/freegle/android/config.xml config.xml
- ln -s ../iznik-nuxt/mobile/freegle/android/package.json package.json
- ln -s ../iznik-nuxt/mobile/freegle/icons icons
- ln -s ../iznik-nuxt/mobile/freegle/package-assets package-assets
- ln -s ../iznik-nuxt/mobile/freegle/scripts scripts
- cp ../iznik-nuxt/google-services.json google-services.json
- ln -s ../iznik-nuxt/dist www
- cordova platform rm android
- cordova platform add android
- cordova build -- --keystore="../iznik-nuxt/android-chrisphdcccom.new.keystore" --storePassword="$storepass"
  --password="$keypass" --alias="$keystorealias"
- cd ../iznik-nuxt
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_deploy:
- git config --local user.name "$gitusername"
- git config --local user.email "$gitemail"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
