#!/bin/bash
# Script to deploy code in our environment.  See ecosystem.config.js for the details of the environment.

if [ "$#" -ne 1 ]
then
 echo "This script takes one argument, production|development|debug"
 exit 1
fi

# Check the environment
ENV=$1

if [[ "$ENV" != "production" && "$ENV" != "development" && "$ENV" != "debug" ]]
then
  echo "Invalid environment."
  exit 2
fi

# Sort out some things which have on occasion blocked deployment
git checkout -- package-lock.json && \
git checkout -- static/sw.js && \
git checkout -- nuxt.config.js && \
npm rebuild node-sass --force && \
git reset --hard HEAD && \
git pull && \
npm install && \
npx patch-package && \
npm run build && \
php ./mungeindex.php > /tmp/a.a && cp /tmp/a.a .nuxt/index.js

# Now deploy.
pm2 deploy $ENV update --force

