#!/bin/bash
# We build our code statically using nuxt generate.  This means that we need to update it regularly, so that our explore pages
# stay fairly up to date.  They don't need to be 100% up to the minute - the Browse page will be for logged in users.
npx patch-package

while true
do
  if [ -f /tmp/iznik.build.abort ]
  then
    echo "Build disabled, sleeping"
    sleep 30;
  else
    export NODE_OPTIONS=--max_old_space_size=8192;
    export API=http://fdapilive.ilovefreegle.org/api

    npm install

    # Very occasionally the build seems to hang, so use timeout.
    timeout -k 20 3600 npm run generate --fail-on-error

    if [ $? -eq 0 ]; then
      # Exclude index until we have copied over everything that it might invoke.
      rsync --rsync-path="ionice -c 3 nice rsync" -au --exclude dist/index.html dist/ app4:/var/www/iznik.fdnuxt.static.live/
      rsync --rsync-path="ionice -c 3 nice rsync" -au --exclude dist/index.html dist/ app1:/var/www/iznik.fdnuxt.static.live/
      rsync -au dist/ app4:/var/www/iznik.fdnuxt.static.live/
      rsync -au dist/ app1:/var/www/iznik.fdnuxt.static.live/
    else
      echo "Generate failed!"
    fi
    echo "Sleep"
    sleep 600;
  fi
done
