# app/config/packages/security.yaml
security:
    encoders:
        App\Entity\User:
            algorithm: argon2i

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    role_hierarchy:
        ROLE_READER: ROLE_USER
        ROLE_ADMIN: ROLE_READER

    firewalls:
        main:
            anonymous: ~
            form_login:
                # We use form login.  We don't use symfony for the form, nuxt handles that, but this gives us
                # the server side handling of the POST.
                #
                # This will cause a redirect loop if you access it via a browser.  So don't.
                login_path: /login
                check_path: login_check
                default_target_path: /
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            logout:
                path:     /login
        dev:
           pattern:  ^/(_(profiler|wdt)|css|images|js)/
           security: false

    access_control:
        # Allow access to the main API page (/) and login page anonymously, otherwise require us to be
        # authenticated.
        - { path: ^/login.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/me, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*, roles: [ IS_AUTHENTICATED_FULLY ] }
