# app/config/packages/security.yaml
security:
    encoders:
        App\Entity\User:
            algorithm: argon2i

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    role_hierarchy:
        ROLE_READER: ROLE_USER
        ROLE_ADMIN: ROLE_READER

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
        dev:
           pattern:  ^/(_(profiler|wdt)|css|images|js)/
           security: false

    access_control:
        # Allow access to the main API page (/) and login page anonymously, otherwise require us to be
        # authenticated.
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/.*, roles: [ IS_AUTHENTICATED_FULLY ] }
