# https://circleci.com/developer/orbs/orb/circleci/node
# https://circleci.com/developer/orbs/orb/circleci/gradle
# https://flexpoint.tech/2017/08/29/using-oracles-jdk-in-circleci-with-gradle/
# https://circleci.com/docs/2.0/language-java/

# https://medium.com/tarmac/continuous-delivery-to-test-flight-with-ionic-and-cordova-on-circleci-without-fastlane-58447324f38a

# https://github.com/ngx-rocket/generator-ngx-rocket/issues/162
# https://github.com/ngx-rocket/generator-ngx-rocket/pull/364/commits/b41a54eb3a465ffe4767412971ec99a7c2ddaf23
# https://github.com/ngx-rocket/circleci-dockerfiles/blob/master/cordova/images/Dockerfile
# Runs in /home/circleci/project
version: 2.1

orbs:
  node: circleci/node@4.1.0
  android: circleci/android@0.2.3
  gradle: circleci/gradle@2.2.0

jobs:
  build-and-deploy-android:  
    #executor: node/default
    executor:
      name: android/android
      sdk-version: '28'
    docker:
      #- image: circleci/android:api-28
      - image: circleci/jdk8:0.1.1
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
      # Checkout the code as the first step.
      - checkout
      - run: apt update
      - run: apt install nodejs
      - run: apt install npm
      #- run: ./gradlew dependencies
      #- android/accept-licenses
      #- run: apt install node
      - run: whereis gradlew
      - run: whereis gradle
      #- run: find . name gradle*
      #- run: chmod +x gradlew
      #- run: git checkout app
      #- node/install:
      #    lts: true
      #    #node-version: '12.20'
      - run: npm -v
      - run: node -v

      - run: npm install
      - run: npm install -g cordova@9.0.0
      - run: npm install -g rimraf
      - run: cordova -v

      - run: cd mobile; openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -d -in circleci-secrets.tar.enc -out circleci-secrets.tar -k $CIRCLE_TAR_PWD
      - run: cd mobile; tar -xvf circleci-secrets.tar; ls -l secrets
      #- run: ./gradlew --version

      # The next step will download the dependencies.
      # - run:
      #     name: Download Dependencies
      #     command: ./gradlew androidDependencies
      # Then lint and run your tests!
      # - run:
      #     name: Run Tests
      #     command: ./gradlew lint test

      - run: mkdir releases
      - run: npm run fdapp
      - run: pwd; ls -l mobile/freegle/scripts
      - run: mkdir ../iznik-nuxt-app
      - run: "cd ../iznik-nuxt-app; 
        ln -s ../project/mobile/freegle/android/config.xml config.xml;
        ln -s ../project/mobile/freegle/android/package.json package.json;
        ln -s ../project/mobile/freegle/icons icons;
        ln -s ../project/mobile/freegle/package-assets package-assets;
        ln -s ../project/mobile/freegle/scripts scripts;
        chmod +x scripts/before_build.sh;
        chmod +x scripts/remove_permissions.js;
        cp ../project/mobile/secrets/google-services.json google-services.json;
        ln -s ../project/dist www;
        cordova platform rm android;
        cordova platform add android@8.1.0
      "
      # Build debug build
      - run: cd ../iznik-nuxt-app; cordova build --debug -- --keystore="../project/mobile/android-chrisphdcccom.new.keystore" --storePassword="$storepass" --password="$keypass" --alias="Freegle Ltd Chris"


workflows:
  version: 2
  android:
    jobs:
      - build-and-deploy-android:
          filters:
            branches:
              only:
                - app
