# https://circleci.com/developer/orbs/orb/circleci/node
# https://circleci.com/developer/orbs/orb/circleci/gradle
# https://flexpoint.tech/2017/08/29/using-oracles-jdk-in-circleci-with-gradle/
# https://circleci.com/docs/2.0/language-java/

# https://medium.com/tarmac/continuous-delivery-to-test-flight-with-ionic-and-cordova-on-circleci-without-fastlane-58447324f38a

# https://github.com/ngx-rocket/generator-ngx-rocket/issues/162
# https://github.com/ngx-rocket/generator-ngx-rocket/pull/364/commits/b41a54eb3a465ffe4767412971ec99a7c2ddaf23
# https://github.com/ngx-rocket/circleci-dockerfiles/blob/master/cordova/images/Dockerfile
# Android: runs in /home/circleci/project
# Apple: runs in /Users/distiller/project
version: 2.1

orbs:
  node: circleci/node@4.1.0
  android: circleci/android@0.2.3
  gradle: circleci/gradle@2.2.0

################
workflows:
  version: 2
  build-and-publish:
    jobs:
      #- hold: # Job needs approval to run
      #    type: approval      
      # https://github.com/CircleCI-Public/circleci-demo-ios/blob/master/.circleci/config.yml
      # https://github.com/Freegle/iznik-nuxt/blob/app-ios/.travis.yml
      - build-and-publish-apple:
          filters:
            branches:
              only:
                - app
      #    requires:
      #      - hold
      #- build-and-publish-android:
      #    filters:
      #      branches:
      #        only:
      #          - app
      #    requires:
      #      - hold

################
################ APPLE
jobs:
  build-and-publish-apple:
    macos:
      # https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
      xcode: "11.3.1" # 12.3.0
    steps:
      - checkout
      - node/install:
          lts: true
          #node-version: "12.20"
      - run: npm -v; node -v # 6.14.11 v14.15.4
################
      - run:
          name: == Decrypt secrets and set up signing
          command: echo "Decrypt secrets"
      - run: openssl version; tar --version; java -version
      #- run: cd mobile; openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -d -in circleci-secrets.tar.enc -out circleci-secrets.tar -k $CIRCLE_TAR_PWD
      - run: cd mobile; openssl enc -aes-256-cbc -md sha512 -salt -d -in circleci-secrets.tar.enc -out circleci-secrets.tar -k $CIRCLE_TAR_PWD
      - run: cd mobile; tar -xvf circleci-secrets.tar --no-same-owner; ls -l secrets

      - run: chmod +x mobile/add-key.sh
      - run: ./mobile/add-key.sh

################
      - run:
          name: == Extract app version strings
          command: echo "Extract app version strings"
      - run: grep -o "MOBILE_VERSION = '[^']*'" nuxt.config.js | sed -e "s/.*MOBILE_VERSION = '//; s/'.*//" >MOBILE_VERSION.txt
      - run: echo "export MOBILE_VERSION=$(<MOBILE_VERSION.txt)" >> $BASH_ENV
      - run: echo $MOBILE_VERSION

      - run: grep -o "MODTOOLS_VERSION = '[^']*'" nuxt.config.js | sed -e "s/.*MODTOOLS_VERSION = '//; s/'.*//" >MODTOOLS_VERSION.txt
      - run: echo "export MODTOOLS_VERSION=$(<MODTOOLS_VERSION.txt)" >> $BASH_ENV
      - run: echo $MODTOOLS_VERSION

      - run: mkdir releases

################
      - run: npm install -g cordova rimraf
      - run: node --version # v14.15.4
      - run: npm --version # 6.14.11
      - run: npm install

################
# FREEGLE app
      - run: npm run fdapp


      - run: mkdir ../iznik-nuxt-app
      - run: cd ../iznik-nuxt-app; ln -s ../project/mobile/freegle/ios/config.xml config.xml
      - run: cd ../iznik-nuxt-app; ln -s ../project/mobile/freegle/ios/package.json package.json
      - run: cd ../iznik-nuxt-app; ln -s ../project/mobile/freegle/icons icons
      - run: cd ../iznik-nuxt-app; ln -s ../project/mobile/freegle/package-assets package-assets
      - run: cd ../iznik-nuxt-app; ln -s ../project/mobile/freegle/scripts scripts
      - run: cd ../iznik-nuxt-app; cp ../project/mobile/secrets/GoogleService-Info.plist GoogleService-Info.plist
      - run: cd ../iznik-nuxt-app; ln -s ../project/dist www
      - run: cd ../iznik-nuxt-app; sudo cordova platform rm ios
      - run: cd ../iznik-nuxt-app; cordova platform add ios@5.1.1

      # Fix cordova-ios
      - run: cd ../iznik-nuxt-app; sed -i '' "s/PROVISIONING_PROFILE =/PROVISIONING_PROFILE_SPECIFIER =/" platforms/ios/cordova/lib/build.js

      # Build debug build
      - run: cd ../iznik-nuxt-app; cordova build --debug --device --codeSignIdentity="iPhone Distribution" --developmentTeam="$iosDeveloper" --packageType="ad-hoc" --automaticProvisioning="false" --provisioningProfile="Freegle adhoc 0420" >buildlogdebug.txt
      - run: cd ../iznik-nuxt-app; cp platforms/ios/build/device/Freegle.ipa ../project/releases/Freegle-ios-app-$MOBILE_VERSION-debug-$(date +'%Y%m%d%H%M%S').ipa

      # Build release build and publish
      - run: cd ../iznik-nuxt-app; cordova build --release --device --codeSignIdentity="iPhone Distribution" --developmentTeam="$iosDeveloper" --packageType="app-store" --automaticProvisioning="false" --provisioningProfile="Freegle 0420"  >buildlogrelease.txt
      - run: cd ../iznik-nuxt-app; cp platforms/ios/build/device/Freegle.ipa ../project/releases/Freegle-ios-app-$MOBILE_VERSION-release-$(date +'%Y%m%d%H%M%S').ipa
      - run: cd ../iznik-nuxt-app; xcrun altool --upload-app --type ios --file "platforms/ios/build/device/Freegle.ipa" --username $AppleUserId --password "$AppleAppSpecificPwd" || true


      # https://circleci.com/docs/2.0/deploying-ios/#section=deployment
      #- deploy:
      #    name: Deploy
      #    command: fastlane release_appstore

################
################ ANDROID

  build-and-publish-android:  
    #executor: node/default
    executor:
      name: android/android
      sdk-version: '28'
    docker:
###      - image: circleci/android:api-28
      - image: circleci/android:api-24-alpha # brings in suitably old openjdk
##      - image: circleci/jdk8:0.1.1
    environment:
      # JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      # ANDROID_HOME: /usr/local/android-sdk-linux
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3g
      _JAVA_OPTIONS: "-Xmx3g"
      TERM: dumb
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
      - run:
          name: == Install
          command: echo "Install"
      - checkout
      - android/accept-licenses
      - node/install:
          lts: true
          #node-version: '12.20'
      - run: npm -v; node -v # 6.14.11 v14.15.4

      - run: npm install
      - run: npm install -g cordova@9.0.0 rimraf
      - run: cordova -v

################
      - run:
          name: == Decrypt secrets 
          command: echo "Decrypt secrets"
      - run: sudo apt update
      - run: openssl version; tar --version; java -version
      #- run: cd mobile; openssl enc -aes-256-cbc -md sha512 -pbkdf2 -iter 100000 -salt -d -in circleci-secrets.tar.enc -out circleci-secrets.tar -k $CIRCLE_TAR_PWD
      - run: cd mobile; openssl enc -aes-256-cbc -md sha512 -salt -d -in circleci-secrets.tar.enc -out circleci-secrets.tar -k $CIRCLE_TAR_PWD
      - run: cd mobile; tar -xvf circleci-secrets.tar --no-same-owner; ls -l secrets

################
      - run:
          name: == Install gradle
          command: echo "Install gradle"
      - run: sudo apt-get install unzip
      - run: wget -O ~/gradle-5.4.1-bin.zip https://services.gradle.org/distributions/gradle-5.4.1-bin.zip
      - run: sudo mkdir /opt/gradle
      - run: sudo unzip -d /opt/gradle ~/gradle-5.4.1-bin.zip
      - run: sudo echo "export GRADLE_HOME=/opt/gradle/gradle-5.4.1" >> $BASH_ENV
      - run: sudo echo "export PATH=$GRADLE_HOME/bin:$PATH" >> $BASH_ENV
      - run: gradle -v
      
################
      - run:
          name: == Extract app version strings
          command: echo "Extract app version strings"
      - run: grep -o "MOBILE_VERSION = '[^']*'" nuxt.config.js | sed -e "s/.*MOBILE_VERSION = '//; s/'.*//" >MOBILE_VERSION.txt
      - run: echo "export MOBILE_VERSION=$(<MOBILE_VERSION.txt)" >> $BASH_ENV
      #- run: echo $MOBILE_VERSION
      - run: grep -o "MODTOOLS_VERSION = '[^']*'" nuxt.config.js | sed -e "s/.*MODTOOLS_VERSION = '//; s/'.*//" >MODTOOLS_VERSION.txt
      - run: echo "export MODTOOLS_VERSION=$(<MODTOOLS_VERSION.txt)" >> $BASH_ENV
      #- run: echo $MODTOOLS_VERSION

      - run: mkdir releases
################
# FREEGLE APP
      - run:
          name: == Make Freegle app debug and release builds and upload to Google Play beta
          command: echo "Make Freegle app"
      - run: npm run fdapp
      - run: pwd; ls -l mobile/freegle/scripts
      - run: mkdir ../iznik-nuxt-app
      - run: "cd ../iznik-nuxt-app; 
        ln -s ../project/mobile/freegle/android/config.xml config.xml;
        ln -s ../project/mobile/freegle/android/package.json package.json;
        ln -s ../project/mobile/freegle/icons icons;
        ln -s ../project/mobile/freegle/package-assets package-assets;
        ln -s ../project/mobile/freegle/scripts scripts;
        chmod +x scripts/before_build.sh;
        chmod +x scripts/remove_permissions.js;
        cp ../project/mobile/secrets/google-services.json google-services.json;
        ln -s ../project/dist www;
        cordova platform rm android;
        cordova platform add android@8.1.0
      "

      - run: echo $ANDROID_HOME
      - run: echo $JAVA_HOME
      # Build debug build
      - run: cd ../iznik-nuxt-app; cordova build --debug -- --keystore="../project/mobile/secrets/android-chrisphdcccom.new.keystore" --storePassword="$storepass" --password="$keypass" --alias="Freegle Ltd Chris"
      - run: cd ../iznik-nuxt-app; cp platforms/android/app/build/outputs/apk/debug/app-debug.apk ../project/releases/Freegle-android-app-$MOBILE_VERSION-debug-$(date +'%Y%m%d%H%M%S').apk

      # Build release build
      - run: cd ../iznik-nuxt-app; cordova build --release -- --keystore="../project/mobile/secrets/android-chrisphdcccom.new.keystore" --storePassword="$storepass" --password="$keypass" --alias="Freegle Ltd Chris"
      - run: cd ../iznik-nuxt-app; cp platforms/android/app/build/outputs/apk/release/app-release.apk ../project/releases/Freegle-android-app-$MOBILE_VERSION-release-$(date +'%Y%m%d%H%M%S').apk

      - run: ls -l releases

      # Publish to Google Play beta track
      - run: cd ../iznik-nuxt-app; sed -i "/3.3.0'/aclasspath 'com.github.triplet.gradle:play-publisher:2.0.0-rc1'" platforms/android/build.gradle
      - run: cd ../iznik-nuxt-app; cat platforms/android/build.gradle
      - run: cd ../iznik-nuxt-app; cp ../project/mobile/build-extras.gradle platforms/android/app
      - run: cd ../iznik-nuxt-app; cp ../project/mobile/secrets/api-freegle-google-play-deployment.json platforms/android/app
      - run: cd ../iznik-nuxt-app/platforms/android; gradle app:publishReleaseApk || true # Ignore errors ie if versionCode already submitted

################
# MODTOOLS APP
      - run:
          name: == Make ModTools app debug and release builds and upload to Google Play beta
          command: echo "Make ModTools app"
      - run: npm run mtapp
      - run: pwd; ls -l mobile/modtools/scripts
      - run: mkdir ../iznik-nuxt-mt
      - run: "cd ../iznik-nuxt-mt; 
        ln -s ../project/mobile/modtools/android/config.xml config.xml;
        ln -s ../project/mobile/modtools/android/package.json package.json;
        ln -s ../project/mobile/modtools/icons icons;
        ln -s ../project/mobile/modtools/package-assets package-assets;
        ln -s ../project/mobile/modtools/scripts scripts;
        chmod +x scripts/before_build.sh;
        cp ../project/mobile/secrets/google-services.json google-services.json;
        ln -s ../project/dist www;
        cordova platform rm android;
        cordova platform add android@8.1.0
      "

      - run: echo $ANDROID_HOME
      - run: echo $JAVA_HOME
      # Build debug build
      - run: cd ../iznik-nuxt-mt; cordova build --debug -- --keystore="../project/mobile/secrets/android-chrisphdcccom.new.keystore" --storePassword="$storepass" --password="$keypass" --alias="Freegle Ltd Chris"
      - run: cd ../iznik-nuxt-mt; cp platforms/android/app/build/outputs/apk/debug/app-debug.apk ../project/releases/ModTools-android-app-$MODTOOLS_VERSION-debug-$(date +'%Y%m%d%H%M%S').apk

      # Build release build
      - run: cd ../iznik-nuxt-mt; cordova build --release -- --keystore="../project/mobile/secrets/android-chrisphdcccom.new.keystore" --storePassword="$storepass" --password="$keypass" --alias="Freegle Ltd Chris"
      - run: cd ../iznik-nuxt-mt; cp platforms/android/app/build/outputs/apk/release/app-release.apk ../project/releases/ModTools-android-app-$MODTOOLS_VERSION-release-$(date +'%Y%m%d%H%M%S').apk

      - run: ls -l releases

      # Publish to Google Play beta track
      - run: cd ../iznik-nuxt-mt; sed -i "/3.3.0'/aclasspath 'com.github.triplet.gradle:play-publisher:2.0.0-rc1'" platforms/android/build.gradle
      - run: cd ../iznik-nuxt-mt; cat platforms/android/build.gradle
      - run: cd ../iznik-nuxt-mt; cp ../project/mobile/build-extras.gradle platforms/android/app
      - run: cd ../iznik-nuxt-mt; cp ../project/mobile/secrets/api-freegle-google-play-deployment.json platforms/android/app
      - run: cd ../iznik-nuxt-mt/platforms/android; gradle app:publishReleaseApk || true # Ignore errors ie if versionCode already submitted

################
# UPLOAD TO GITHUB AS NEW TAGGED RELEASE
      - run:
          name: == Upload created apks as a tagged github release
          command: echo "Upload to github"
      - run: git config --local user.name "$gitusername"
      - run: git config --local user.email "$gitemail"
      - run: echo "export CIRCLECI_TAG=circleci-android-builds-fd$MOBILE_VERSION-mt$MODTOOLS_VERSION-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)" >> $BASH_ENV
      - run: echo $CIRCLECI_TAG
      - run: git tag $CIRCLECI_TAG

      # https://circleci.com/blog/publishing-to-github-releases-via-circleci/
      # https://github.com/tcnksm/ghr
      - run: wget https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_386.tar.gz
      - run: tar -xvzf ghr_v0.13.0_linux_386.tar.gz
      - run: ls -l ghr_v0.13.0_linux_386
      - run: chmod +x ghr_v0.13.0_linux_386/ghr

      - run: ghr_v0.13.0_linux_386/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLECI_TAG} ./releases/

################
# STORE RELEASE IN CIRCLE-CI ARTIFACTS
      - run:
          name: == Store built apks as circle-ci artifects
          command: echo "Store as circle-ci artifects"
      - store_artifacts:
          path: ./releases
