# https://circleci.com/developer/orbs/orb/circleci/node
# https://circleci.com/developer/orbs/orb/circleci/gradle
version: 2.1

orbs:
  node: circleci/node@4.1.0
  gradle: circleci/gradle@2.2.0

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-deploy-android:  
    # These next lines define a docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # Be sure to update the docker image tag below to android api version of your application.
    executor: node/default
    docker:
      - image: circleci/android:api-28
    steps:
      # Checkout the code as the first step.
      - checkout
      - run: git checkout app
      - node/install:
          lts: true
          #node-version: '12.20'
      - run: npm -v
      - run: node -v

      - run: npm install
      - run: npm install -g cordova@9.0.0
      - run: npm install -g rimraf
      - run: cordova -v
      #- run: ./gradlew --version

      # The next step will download the dependencies.
      # - run:
      #     name: Download Dependencies
      #     command: ./gradlew androidDependencies
      # Then lint and run your tests!
      # - run:
      #     name: Run Tests
      #     command: ./gradlew lint test

      - run: mkdir releases
      - run: npm run fdapp
      - run: mkdir ../iznik-nuxt-app
      - run: cd ../iznik-nuxt-app; ln -s ../iznik-nuxt/mobile/freegle/android/config.xml config.xml
      - run: cd ../iznik-nuxt-app; ln -s ../iznik-nuxt/mobile/freegle/android/package.json package.json
      - run: cd ../iznik-nuxt-app; ln -s ../iznik-nuxt/mobile/freegle/icons icons
      - run: cd ../iznik-nuxt-app; ln -s ../iznik-nuxt/mobile/freegle/package-assets package-assets
      - run: cd ../iznik-nuxt-app; ln -s ../iznik-nuxt/mobile/freegle/scripts scripts
      - run: cd ../iznik-nuxt-app; ls -l; ls -l scripts
      - run: cd ../iznik-nuxt-app; chmod +x scripts/before_build.sh
      - run: cd ../iznik-nuxt-app; chmod +x scripts/remove_permissions.js
      - run: cd ../iznik-nuxt-app; cp ../iznik-nuxt/google-services.json google-services.json
      - run: cd ../iznik-nuxt-app; ln -s ../iznik-nuxt/dist www
      - run: cd ../iznik-nuxt-app; cordova platform rm android
      - run: cd ../iznik-nuxt-app; cordova platform add android@8.1.0
      # Build debug build
      - run: cd ../iznik-nuxt-app; cordova build --debug -- --keystore="../iznik-nuxt/android-chrisphdcccom.new.keystore" --storePassword="$storepass" --password="$keypass" --alias="Freegle Ltd Chris"


workflows:
  version: 2
  android:
    jobs:
      - build-and-deploy-android:
          filters:
            branches:
              only:
                - app
