export const SLOT_DELETE_RESET = 'SLOT_DELETE_RESET'
export const SLOT_DELETE_SET_ERROR = 'SLOT_DELETE_SET_ERROR'
export const SLOT_DELETE_SET_DELETED = 'SLOT_DELETE_SET_DELETED'
export const SLOT_DELETE_TOGGLE_LOADING = 'SLOT_DELETE_TOGGLE_LOADING'
