import Vue from 'vue'
import Icon from 'vue-awesome/components/Icon.vue'

// We list the icons we use explicitly because this reduces our bundle size.
require('vue-awesome/icons/address-book')
require('vue-awesome/icons/angle-double-right')
require('vue-awesome/icons/bell')
require('vue-awesome/icons/bullhorn')
require('vue-awesome/icons/calendar-alt')
require('vue-awesome/icons/camera')
require('vue-awesome/icons/caret-down')
require('vue-awesome/icons/caret-up')
require('vue-awesome/icons/chart-bar')
require('vue-awesome/icons/check')
require('vue-awesome/icons/check-circle')
require('vue-awesome/icons/circle')
require('vue-awesome/icons/cog')
require('vue-awesome/icons/clock')
require('vue-awesome/icons/coffee')
require('vue-awesome/icons/comment')
require('vue-awesome/icons/comments')
require('vue-awesome/icons/crown')
require('vue-awesome/icons/envelope')
require('vue-awesome/icons/exclamation-triangle')
require('vue-awesome/icons/eye')
require('vue-awesome/icons/frown')
require('vue-awesome/icons/gift')
require('vue-awesome/icons/globe-europe')
require('vue-awesome/icons/handshake')
require('vue-awesome/icons/heart')
require('vue-awesome/icons/home')
require('vue-awesome/icons/info-circle')
require('vue-awesome/icons/leaf')
require('vue-awesome/icons/lock')
require('vue-awesome/icons/meh')
require('vue-awesome/icons/map-marker-alt')
require('vue-awesome/icons/pen')
require('vue-awesome/icons/plus')
require('vue-awesome/icons/question-circle')
require('vue-awesome/icons/reply')
require('vue-awesome/icons/save')
require('vue-awesome/icons/search')
require('vue-awesome/icons/share-alt')
require('vue-awesome/icons/sign-out-alt')
require('vue-awesome/icons/slash')
require('vue-awesome/icons/smile')
require('vue-awesome/icons/star')
require('vue-awesome/icons/sync')
require('vue-awesome/icons/thumbs-down')
require('vue-awesome/icons/thumbs-up')
require('vue-awesome/icons/times')
require('vue-awesome/icons/times-circle')
require('vue-awesome/icons/trash-alt')
require('vue-awesome/icons/user')
require('vue-awesome/icons/users')
require('vue-awesome/icons/window-maximize')
require('vue-awesome/icons/window-restore')

require('vue-awesome/icons/brands/facebook')
require('vue-awesome/icons/brands/google-plus')
require('vue-awesome/icons/brands/pinterest')
require('vue-awesome/icons/brands/skype')
require('vue-awesome/icons/brands/telegram')
require('vue-awesome/icons/brands/twitter')
require('vue-awesome/icons/brands/whatsapp')

Vue.component('v-icon', Icon)
