export const PERSON_SHOW_RESET = 'PERSON_SHOW_RESET'
export const PERSON_SHOW_SET_ERROR = 'PERSON_SHOW_SET_ERROR'
export const PERSON_SHOW_SET_RETRIEVED = 'PERSON_SHOW_SET_RETRIEVED'
export const PERSON_SHOW_TOGGLE_LOADING = 'PERSON_SHOW_TOGGLE_LOADING'
