export const PERSON_DELETE_RESET = 'PERSON_DELETE_RESET'
export const PERSON_DELETE_SET_ERROR = 'PERSON_DELETE_SET_ERROR'
export const PERSON_DELETE_SET_DELETED = 'PERSON_DELETE_SET_DELETED'
export const PERSON_DELETE_TOGGLE_LOADING = 'PERSON_DELETE_TOGGLE_LOADING'
