export const LOCATION_DELETE_RESET = 'LOCATION_DELETE_RESET'
export const LOCATION_DELETE_SET_ERROR = 'LOCATION_DELETE_SET_ERROR'
export const LOCATION_DELETE_SET_DELETED = 'LOCATION_DELETE_SET_DELETED'
export const LOCATION_DELETE_TOGGLE_LOADING = 'LOCATION_DELETE_TOGGLE_LOADING'
